### PR TITLE
Update user permissions in namespace creation

### PR DESCRIPTION
**Pull request by tszczyp**
Updated createNamespace.sh:
Added new variable user, changed chmod permissions to chown.

Changes are made due to "permission denied" errors, while the user running tests is not root.

Signed-off-by: Tomasz Szczypiorowski <tomaszx.szczypiorowski@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)* status: all files reviewed, 3 unresolved discussions (waiting on @tszczyp)

___
*[jenkins/scripts/createNamespace.sh, line 21 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-Mkw4yrp4sy0owdrgWz0:-Mkw4yrp4sy0owdrgWz1:b9w55a2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/bb5c07042427731f5ad488159fc7673bbfce8edd/jenkins/scripts/createNamespace.sh#L21)):*
> ```Shell
> SIZE=100G
> # During the namespace creation, this user will gain access to files necessary to run tests.
> # This is done to allow non root users to start execution.
> ```

This comment seems a little too complicated. Perhaps simply:
`This user will be set as an owner of created namespace(s). It's required e.g. for pool creation in tests.`
___
*[jenkins/scripts/createNamespace.sh, line 95 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-Mkw48cf4AeKVoZVsGHD:-Mkw48cgCOI3gMy3AJL2:bwpaqwv) ([raw file](https://github.com/pmem/dev-utils-kit/blob/bb5c07042427731f5ad488159fc7673bbfce8edd/jenkins/scripts/createNamespace.sh#L95)):*
> ```Shell
> if $CREATE_DAX; then
> 	create_devdax 4k $SIZE
> 	# Setting DAX specific permission.
> ```

this comment should be updated, I guess
___
*[jenkins/scripts/createNamespace.sh, line 114 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-Mkw4D5K1trx2l1koye4:-Mkw4D5K1trx2l1koye5:bs0vdsz) ([raw file](https://github.com/pmem/dev-utils-kit/blob/bb5c07042427731f5ad488159fc7673bbfce8edd/jenkins/scripts/createNamespace.sh#L114)):*
> ```Shell
> 		sudo mkfs.ext4 -F /dev/$pmem_name
> 		sudo mount -o dax /dev/$pmem_name $MOUNTPOINT
> 		# We mount only FSDAX namespaces.
> ```

I'm not sure what is this comment related to, perhaps update it as well...?

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[jenkins/scripts/createNamespace.sh, line 21 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-Mkw4yrp4sy0owdrgWz0:-Ml9eRnrAkoDbHjt7at5:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/bb5c07042427731f5ad488159fc7673bbfce8edd/jenkins/scripts/createNamespace.sh#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

This comment seems a little too complicated. Perhaps simply:
`This user will be set as an owner of created namespace(s). It's required e.g. for pool creation in tests.`
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 95 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-Mkw48cf4AeKVoZVsGHD:-Ml9eSMw52gXPtTfrGVY:b-xkkst3) ([raw file](https://github.com/pmem/dev-utils-kit/blob/bb5c07042427731f5ad488159fc7673bbfce8edd/jenkins/scripts/createNamespace.sh#L95)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this comment should be updated, I guess
</blockquote></details>

This should make more sense.
___
*[jenkins/scripts/createNamespace.sh, line 114 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-Mkw4D5K1trx2l1koye4:-Ml9eWX44nU3dC9SeISA:b-bu91xm) ([raw file](https://github.com/pmem/dev-utils-kit/blob/bb5c07042427731f5ad488159fc7673bbfce8edd/jenkins/scripts/createNamespace.sh#L114)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure what is this comment related to, perhaps update it as well...?
</blockquote></details>

Updated

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-:-Ml9mDj68y9V6hvto9l2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tszczyp)

**Review by nedved1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)* status: all files reviewed, 1 unresolved discussion (waiting on @tszczyp)

___
*[jenkins/scripts/createNamespace.sh, line 21 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-MlA6dRi3OfklNUtXFrs:-MlA6dRi3OfklNUtXFrt:b-s7z88e) ([raw file](https://github.com/pmem/dev-utils-kit/blob/e5c9f78d4d7d57fcccdd58ea45e18503d406e82f/jenkins/scripts/createNamespace.sh#L21)):*
> ```Shell
> SIZE=100G
> # This user will be set as an owner of created namespace(s). It's required e.g. for pool creation in tests.
> USERNAME=test-user
> ```

Please make it `USERNAME=$(whoami)`. It will grab the name of the current user, making this script more universal.

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @nedved1)

___
*[jenkins/scripts/createNamespace.sh, line 21 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-MlA6dRi3OfklNUtXFrs:-MlEjyRT1SfL0A0orXU-:bxwd9z8) ([raw file](https://github.com/pmem/dev-utils-kit/blob/e5c9f78d4d7d57fcccdd58ea45e18503d406e82f/jenkins/scripts/createNamespace.sh#L21)):*
<details><summary><i>Previously, nedved1 (Pawel Niedzwiecki) wrote…</i></summary><blockquote>

Please make it `USERNAME=$(whoami)`. It will grab the name of the current user, making this script more universal.
</blockquote></details>

I agree. Done

**Comment by lukaszstolarczuk** [comment]
> > _[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)_ status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @nedved1)
> 
> _[jenkins/scripts/createNamespace.sh, line 21 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-MlA6dRi3OfklNUtXFrs:-MlEjyRT1SfL0A0orXU-:bxwd9z8) ([raw file](https://github.com/pmem/dev-utils-kit/blob/e5c9f78d4d7d57fcccdd58ea45e18503d406e82f/jenkins/scripts/createNamespace.sh#L21)):_
> 
> Previously, nedved1 (Pawel Niedzwiecki) wrote…
> I agree. Done

Please test this work e.g. in pmemkv job, so we're not surprised anymore 😃

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @nedved1)

___
*[jenkins/scripts/createNamespace.sh, line 21 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-MlA6dRi3OfklNUtXFrs:-MlFUYaQ1D22DqKxP89w:b46puu7) ([raw file](https://github.com/pmem/dev-utils-kit/blob/e5c9f78d4d7d57fcccdd58ea45e18503d406e82f/jenkins/scripts/createNamespace.sh#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Please test this work e.g. in pmemkv job, so we're not surprised anymore 😃 
</blockquote></details>

I've relaunched libpmemobj-cpp tests locally after Pawel's update and everything seems to work fine :)

**Review by nedved1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @tszczyp)

___
*[jenkins/scripts/createNamespace.sh, line 21 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-MlA6dRi3OfklNUtXFrs:-MlFWIeH7cHL4K3v2HVo:bb7p58j) ([raw file](https://github.com/pmem/dev-utils-kit/blob/e5c9f78d4d7d57fcccdd58ea45e18503d406e82f/jenkins/scripts/createNamespace.sh#L21)):*
<details><summary><i>Previously, tszczyp (Tomasz Szczypiorowski) wrote…</i></summary><blockquote>

I've relaunched libpmemobj-cpp tests locally after Pawel's update and everything seems to work fine :) 
</blockquote></details>

thnx

**Review by nedved1 — COMMENTED** [review]
:ok_hand: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-:-MlFXFLB8S14Qbw8k7cA:b4putsz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tszczyp)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)* status: all files reviewed, 2 unresolved discussions (waiting on @tszczyp)

___
*[jenkins/scripts/createNamespace.sh, line 20 at r3](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-MlFkmG0ELgxrl5LViAW:-MlFkmG1AeryodXEFyRp:bat34t0) ([raw file](https://github.com/pmem/dev-utils-kit/blob/d363114f3854c52bf29abca775c93078cde19ac0/jenkins/scripts/createNamespace.sh#L20)):*
> ```Shell
> # The default size of namespaces.
> SIZE=100G
> # This user will be set as an owner of created namespace(s). It's required e.g. for pool creation in tests.
> ```

the created
___
*[jenkins/scripts/createNamespace.sh, line 95 at r3](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-MlFkD8e7SPhv0XPK1IZ:-MlFkD8e7SPhv0XPK1I_:b-uk001u) ([raw file](https://github.com/pmem/dev-utils-kit/blob/d363114f3854c52bf29abca775c93078cde19ac0/jenkins/scripts/createNamespace.sh#L95)):*
> ```Shell
> 	create_devdax 4k $SIZE
> 	# Setting DAX ownership for the specific user.
> 	sudo chown -R $USERNAME /dev/dax*
> ```

`-R` is unnecessary here.

**Review by tszczyp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @nedved1)

___
*[jenkins/scripts/createNamespace.sh, line 20 at r3](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-MlFkmG0ELgxrl5LViAW:-MlTpngiEOmApZ_hVyJO:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/d363114f3854c52bf29abca775c93078cde19ac0/jenkins/scripts/createNamespace.sh#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the created
</blockquote></details>

Done.
___
*[jenkins/scripts/createNamespace.sh, line 95 at r3](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-MlFkD8e7SPhv0XPK1IZ:-MlTpozb5SgSWUog2Qqx:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/d363114f3854c52bf29abca775c93078cde19ac0/jenkins/scripts/createNamespace.sh#L95)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`-R` is unnecessary here.
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by tszczyp — COMMENTED** [review]
Do you have any other suggestions or can it be merged?

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-:-MlsXnio63mrwM0wSziJ:bsnrwm2)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/3#-:-MmRxX0n3Of39seV-QdF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tszczyp)

**Pull request merged**
