### PR TITLE
CI: add GHA with job re-building and pushing images

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- [x] need to wait for #6, to test this change properly on my fork with the images

Thanks to this PR we can push "base pmem" images into GH registry and start using them in projects (starting e.g. in pmemstream).
This PR is partially based on current versions of scripts from libpmemobj-cpp repository.

Preview of published packages on my fork:
build: https://github.com/lukaszstolarczuk/dev-utils-kit/runs/4251141542?check_suite_focus=true
packages: https://github.com/lukaszstolarczuk/dev-utils-kit/pkgs/container/dev-utils-kit

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/5)

### CODE REVIEW

**Comment by karczex** [comment]
___
*[docker/README.md, line 23 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/5#-Mn_FCO-70NHbDpFxEpn:-Mn_FCO-70NHbDpFxEpo:b-j00xfo) ([raw file](https://github.com/pmem/dev-utils-kit/blob/7f14f6fbef02e73c77ec5827359e677f507b0f35/docker/README.md#L23)):*
> ```
> -e CC=clang -e CXX=clang++ -e PKG_CONFIG_PATH=/opt/pmdk/lib/pkgconfig 
> ```
This part is probably not enough generic

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/5)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[.github/workflows/main.yml, line 2 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/5#-Mn_CfHs-XeozRswINHE:-Mn_CfHs-XeozRswINHF:b-k84uq2) ([raw file](https://github.com/pmem/dev-utils-kit/blob/7f14f6fbef02e73c77ec5827359e677f507b0f35/.github/workflows/main.yml#L2)):*
> ```YAML
> 
> name: dev-utils-kit
> ```

I would rather name it "docker-images"

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/5)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[.github/workflows/main.yml, line 2 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/5#-Mn_CfHs-XeozRswINHE:-Mn_Mmij0r9u3BJ9p8fe:b-rdppoq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/7f14f6fbef02e73c77ec5827359e677f507b0f35/.github/workflows/main.yml#L2)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I would rather name it "docker-images"
</blockquote></details>

I wanted to squeeze here executing checks on this repo AND building images, but split makes probably more sense - so the new name is more accurate - thx
___
*[docker/README.md, line 23 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/5#-Mn_FCO-70NHbDpFxEpn:-Mn_NNzF2MEPEFSxrP38:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/7f14f6fbef02e73c77ec5827359e677f507b0f35/docker/README.md#L23)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> -e CC=clang -e CXX=clang++ -e PKG_CONFIG_PATH=/opt/pmdk/lib/pkgconfig 
> ```
This part is probably not enough generic 
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
I can't give "approve" due to permissions

> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/5#-:-MnzX4vI26ntugG0JxQo:b3iwv9g)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Comment by karczex** [comment]
___
*[docker/pull-or-rebuild-image.sh, line 110 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/5#-MomY79p-bI1wOWsQr3k:-MomY79p-bI1wOWsQr3l:b-1g67jq) ([raw file](https://github.com/pmem/dev-utils-kit/blob/0f7040a618caf1b205a2462514c9688d8afa94ec/docker/pull-or-rebuild-image.sh#L110)):*
> ```Shell
> for file in ${files}; do
> 	# Check if modified files are relevant to the current build
> 	if [[ ${file} =~ ^(${BASE_DIR})\/Dockerfile\.(${OS})-(${OS_VER})$ ]] \
> ```

Please update to new naming convention

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/5)* status: 1 of 13 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[docker/pull-or-rebuild-image.sh, line 110 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/5#-MomY79p-bI1wOWsQr3k:-Mon1ToV8pg51QGdWvTM:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/0f7040a618caf1b205a2462514c9688d8afa94ec/docker/pull-or-rebuild-image.sh#L110)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Please update to new naming convention
</blockquote></details>

Done.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/5#-:-Mono9jz747acrp7LLdY:bnfp4nl)* status: 1 of 13 files reviewed, all discussions resolved (waiting on @karczex and @KFilipek)

**Pull request merged**
