### PR TITLE
Initial dockerfiles

### PR DESCRIPTION
**Pull request by KFilipek**
Add Docker files for Ubuntu and Fedora.

Source PR: #4

List of commits:
﻿- Initial dockerfile for fedora34
- Add new dockerfiles for Ubuntu and Fedora.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/6)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/6)* status: all files reviewed, 5 unresolved discussions (waiting on @KFilipek)

___
*[Docker/fedora33.Dockerfile, line 20 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIPZjz7yzQsyXfKnp6:-MoIPZjz7yzQsyXfKnp7:b-uxig1v) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/fedora33.Dockerfile#L20)):*
> ```
> ARG BASE_DEPS="\
> 	cmake \
> 	clang \
> ```

as I pointed to Paweł already - we can live without `clang`, it's not a base requirement, we only use it in our CI in tests
(pls move it to MISC_DEPS in all images)
___
*[Docker/fedora33.Dockerfile, line 27 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIODvJ8xz4n8gkNyJK:-MoIODvJ8xz4n8gkNyJL:bvyko4u) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/fedora33.Dockerfile#L27)):*
> ```
> 	rpm-build \
> 	rpm-build-libs \
> 	rpmdevtools"
> ```

these last 3 are only required for building PMDK, please move to PMDK_DEPS 
(pls fix in both Fedora images)
___
*[Docker/ubuntu20.04.Dockerfile, line 35 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIPBox5corTnZo_Tkm:-MoIPBox5corTnZo_Tkn:b8f9rzj) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L35)):*
> ```
> 	libndctl-dev \
> 	devscripts \
> 	build-essential \
> ```

you can move `build-essential` into BASE_DEPS, since it covers make, gcc, g++
(pls fix in all Ubuntu images)
___
*[Docker/ubuntu20.04.Dockerfile, line 57 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIWl2T0geqLmaUDmk7:-MoIWl2T0geqLmaUDmk8:b-yircp9) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L57)):*
> ```
> # Misc for our builds/CI (optional)
> ARG MISC_DEPS="\
> 	hub \
> ```

in all our projects we run "docs update" only on Fedora images, `hub` package on Ubuntu seems redundant
(pls fix in all Ubuntu images)
___
*[Docker/ubuntu20.04.Dockerfile, line 65 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIVahmAhmfWlzIEJAL:-MoIVahmAhmfWlzIEJAM:bl93g0t) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L65)):*
> ```
> # Coverity
> ENV COVERITY_DEPS "\
> 	wget"
> ```

actually, on Ubuntu Coverity requires: ruby, curl and wget

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/6)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[Docker/fedora33.Dockerfile, line 20 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIPZjz7yzQsyXfKnp6:-Mo_2SlI3UqvsieiQHg_:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/fedora33.Dockerfile#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as I pointed to Paweł already - we can live without `clang`, it's not a base requirement, we only use it in our CI in tests
(pls move it to MISC_DEPS in all images)
</blockquote></details>

Done.
___
*[Docker/fedora33.Dockerfile, line 27 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIODvJ8xz4n8gkNyJK:-Mo_2qO-1mGlJDnwG-1B:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/fedora33.Dockerfile#L27)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

these last 3 are only required for building PMDK, please move to PMDK_DEPS 
(pls fix in both Fedora images)
</blockquote></details>

Done.
___
*[Docker/ubuntu20.04.Dockerfile, line 35 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIPBox5corTnZo_Tkm:-Mo_2yow2pNDmqjSzDD9:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you can move `build-essential` into BASE_DEPS, since it covers make, gcc, g++
(pls fix in all Ubuntu images)
</blockquote></details>

Done.
___
*[Docker/ubuntu20.04.Dockerfile, line 57 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIWl2T0geqLmaUDmk7:-Mo_5-GV2RN9BFnlYvuR:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L57)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in all our projects we run "docs update" only on Fedora images, `hub` package on Ubuntu seems redundant
(pls fix in all Ubuntu images)
</blockquote></details>

Done.
___
*[Docker/ubuntu20.04.Dockerfile, line 65 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIVahmAhmfWlzIEJAL:-Mo_5Xh1CFqkPZXYd62g:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L65)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually, on Ubuntu Coverity requires: ruby, curl and wget
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/6)* status: all files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[Docker/fedora33.Dockerfile, line 34 at r3](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MocF-6nA5ZtMXerkwYc:-MocF-6nA5ZtMXerkwYd:b-evv9zg) ([raw file](https://github.com/pmem/dev-utils-kit/blob/7dbb943c034bed96cc7b902ba5bccaf2732ce0fc/Docker/fedora33.Dockerfile#L34)):*
> ```
> 	python3 \
> 	which \
> 	rpm-build \
> ```

we rather keep alphabetical order of packages (pls fix all newly added packages, incl. PMDK, MISC, and COVERITY deps, in all images)
___
*[Docker/ubuntu20.04.Dockerfile, line 35 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIPBox5corTnZo_Tkm:-MocEBZX9QADQcoNDF4x:bhtcrvc) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L35)):*
> make, gcc, g++
since it covers these 3 packages they can be removed from the list
(pls fix all Ubuntu images)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/6)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[Docker/fedora33.Dockerfile, line 34 at r3](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MocF-6nA5ZtMXerkwYc:-MofCo8q0sbNbBVGuka_:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/7dbb943c034bed96cc7b902ba5bccaf2732ce0fc/Docker/fedora33.Dockerfile#L34)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we rather keep alphabetical order of packages (pls fix all newly added packages, incl. PMDK, MISC, and COVERITY deps, in all images)
</blockquote></details>

Done.
___
*[Docker/ubuntu20.04.Dockerfile, line 35 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIPBox5corTnZo_Tkm:-MofCmFg0WM-bMot9mcM:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

> make, gcc, g++
since it covers these 3 packages they can be removed from the list
(pls fix all Ubuntu images)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/6)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[Docker/ubuntu20.04.Dockerfile, line 35 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIPBox5corTnZo_Tkm:-MogyS1PD63JL6yDlEFw:b-oipjvy) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L35)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done - gcc, g++, and make are redundant if you have build-essential

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/6)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[Docker/ubuntu20.04.Dockerfile, line 35 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-MoIPBox5corTnZo_Tkm:-MojexTz5WcFffJaKZg7:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/55b4c62290448542c617b2fba7a5b792816abb87/Docker/ubuntu20.04.Dockerfile#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not done - gcc, g++, and make are redundant if you have build-essential
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/6#-:-MomBnLcCk7Ax2R0YF87:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
