### PR TITLE
Update dockers

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
the most important change in this PR is to add common installation scripts - for starters: PMDK and libpmemobj-cpp.

I've tested various scenarios, how we do and can use these scripts:
- my testing branch: https://github.com/pmem/dev-utils-kit/compare/master...lukaszstolarczuk:test-update-docker?expand=1
- the results: https://github.com/lukaszstolarczuk/dev-utils-kit/actions/runs/1508371463

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7)* status: all files reviewed, 7 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[docker/images/fedora-33.Dockerfile, line 32 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf9Tus2PsujdwVT_hA:-Mpf9Tus2PsujdwVT_hB:bh7fkle) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/fedora-33.Dockerfile#L32)):*
> ```
> pandoc \
> ```
duplication
___
*[docker/images/fedora-34.Dockerfile, line 32 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf9QDw7I5bJlmBsKsl:-Mpf9QDw7I5bJlmBsKsm:bh7fkle) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/fedora-34.Dockerfile#L32)):*
> ```
> pandoc \
> ```
duplication
___
*[docker/images/install-libpmemobj-cpp.sh, line 8 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf5cKQ2MWoiLYh-PhV:-Mpf5cKRBqa4pCCu_gL9:b6yjze6) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/install-libpmemobj-cpp.sh#L8)):*
> ```
> ··
> ```
trailing spaces
___
*[docker/images/install-libpmemobj-cpp.sh, line 58 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf7659-_hpdZRkyFmZ:-Mpf765A-XVpwVhUvarI:b-2trpig) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/install-libpmemobj-cpp.sh#L58)):*
> ```
> popd
> popd
> ```
or simply
```
dirs -c
```
___
*[docker/images/install-libpmemobj-cpp.sh, line 59 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf5nrd4pdq700hq4M5:-Mpf5nrd4pdq700hq4M6:b6yjze6) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/install-libpmemobj-cpp.sh#L59)):*
> ```
> ··
> ```
trailing spaces
___
*[docker/images/ubuntu-20.04.Dockerfile, line 33 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf9HvO5W0qvUaeUlal:-Mpf9HvO5W0qvUaeUlam:bh7fkle) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/ubuntu-20.04.Dockerfile#L33)):*
> ```
> pandoc \
> ```
duplication
___
*[docker/images/ubuntu-21.10.Dockerfile, line 33 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf9YsQ8iVXhutTokIw:-Mpf9YsQ8iVXhutTokIx:bh7fkle) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/ubuntu-21.10.Dockerfile#L33)):*
> ```
> pandoc \
> ```
duplication

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7)* status: all files reviewed, 7 unresolved discussions (waiting on @KFilipek)

___
*[docker/images/fedora-33.Dockerfile, line 32 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf9Tus2PsujdwVT_hA:-MpfLTaq30c55Xem689u:b-ti2lb6) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/fedora-33.Dockerfile#L32)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> pandoc \
> ```
duplication
</blockquote></details>

that's expected, it's a dependency for both. As you can see, it's not the only duplication in these (e.g. `autoconf`).
___
*[docker/images/fedora-34.Dockerfile, line 32 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf9QDw7I5bJlmBsKsl:-MpfLp4m5AZNGMt1rKiI:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/fedora-34.Dockerfile#L32)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> pandoc \
> ```
duplication
</blockquote></details>

Done.
___
*[docker/images/install-libpmemobj-cpp.sh, line 8 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf5cKQ2MWoiLYh-PhV:-MpfMtNq1g6F7FK3Xwxo:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/install-libpmemobj-cpp.sh#L8)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> ··
> ```
trailing spaces
</blockquote></details>

Done.
___
*[docker/images/install-libpmemobj-cpp.sh, line 58 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf7659-_hpdZRkyFmZ:-MpfM9OxCtSgfkxpUa2U:bta6m1x) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/install-libpmemobj-cpp.sh#L58)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> popd
> popd
> ```
or simply
```
dirs -c
```
</blockquote></details>

nope, it won't work - `dirs -c` only clears the dirs' stack
___
*[docker/images/install-libpmemobj-cpp.sh, line 59 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf5nrd4pdq700hq4M5:-MpfMsgY5O6dEhP1IGGk:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/install-libpmemobj-cpp.sh#L59)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> ··
> ```
trailing spaces
</blockquote></details>

Done.
___
*[docker/images/ubuntu-20.04.Dockerfile, line 33 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf9HvO5W0qvUaeUlal:-MpfMFUa2N5UuoB2KsEB:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/ubuntu-20.04.Dockerfile#L33)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> pandoc \
> ```
duplication
</blockquote></details>

Done.
___
*[docker/images/ubuntu-21.10.Dockerfile, line 33 at r1](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf9YsQ8iVXhutTokIw:-MpfMFvN8DbId398SqMS:b-896fix) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5832567c76428a4d64817839311859517d5d63f0/docker/images/ubuntu-21.10.Dockerfile#L33)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> pandoc \
> ```
duplication
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
LGBT :lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-:-MpkR-FsB7UbuYHcMYLP:br3xlm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by KFilipek — APPROVED** [review]

**Review by karczex — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[docker/images/install-libpmemobj-cpp.sh, line 24 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf_dlHCEDPm9YC1VGs:-Mpf_dlI61F_lQEFpjC0:bef5n63) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5f269a73c813356df68fc525663131ebf680d6fb/docker/images/install-libpmemobj-cpp.sh#L24)):*
> ```Shell
> PACKAGE_TYPE=${PACKAGE_MANAGER^^} # make it uppercase
> # common: 1.13.0 release; 27.07.2021
> CHECKOUT=${LIBPMEMOBJCPP_VERSION:-9599f724d4edc3a3d973bac14eeebdc1bc31d327}
> ```

I would say default value should be `origin/master` or last tag. Probably last tag is better. 
___
*[docker/images/install-pmdk.sh, line 29 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-MpfdiRgDsGPLeBjxLD1:-MpfdiRgDsGPLeBjxLD2:bef5n63) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5f269a73c813356df68fc525663131ebf680d6fb/docker/images/install-pmdk.sh#L29)):*
> ```Shell
> [ "${PACKAGE_TYPE}" == "deb" ] && PACKAGE_TYPE="dpkg" # XXX: PMDK uses different alias
> # master: 1.11.1, 24.09.2021
> CHECKOUT=${PMDK_VERSION:-5b21904a257eff47f2e87fcbf2de46111f03ddd8}
> ```

I would say default value should be `origin/master` or last tag. Probably last tag is better.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[docker/images/install-libpmemobj-cpp.sh, line 24 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Mpf_dlHCEDPm9YC1VGs:-MqJDIqD3uN4yDPx-sFH:b-9nqzt6) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5f269a73c813356df68fc525663131ebf680d6fb/docker/images/install-libpmemobj-cpp.sh#L24)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I would say default value should be `origin/master` or last tag. Probably last tag is better. 
</blockquote></details>

it is the 1.13.0 tag

I prefer to use sha instead of a tag, because it may be not pulled or something.
___
*[docker/images/install-pmdk.sh, line 29 at r2](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-MpfdiRgDsGPLeBjxLD1:-MqJDM5GEFhleVKxFDd_:b-98r8i6) ([raw file](https://github.com/pmem/dev-utils-kit/blob/5f269a73c813356df68fc525663131ebf680d6fb/docker/images/install-pmdk.sh#L29)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I would say default value should be `origin/master` or last tag. Probably last tag is better. 
</blockquote></details>

It is 1.11.1 tag, I fixed the comment a little.

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-:-MqOzKp83MixFgPRCem-:bnfp4nl)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @KFilipek)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 7 of 11 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[docker/images/fedora-35.Dockerfile, line 83 at r5](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Muk-Jta0oyPo8_du4sG:-Muk-Jtb19hkwNFMzhue:b-ya0hjw) ([raw file](https://github.com/pmem/dev-utils-kit/blob/e104a9e3b0a928834a95aac58fa93af2dc3c2fae/docker/images/fedora-35.Dockerfile#L83)):*
> ```
> COPY install-valgrind.sh install-valgrind.sh
> RUN ./install-valgrind.sh
> ```

in other images you also have  such steps:
```
COPY install-pmdk.sh /opt/install-pmdk.sh
COPY install-libpmemobj-cpp.sh /opt/install-libpmemobj-cpp.sh
```

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[docker/images/fedora-35.Dockerfile, line 83 at r5](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-Muk-Jta0oyPo8_du4sG:-Muk5mkW3QkC72S0batf:b5vuy47) ([raw file](https://github.com/pmem/dev-utils-kit/blob/e104a9e3b0a928834a95aac58fa93af2dc3c2fae/docker/images/fedora-35.Dockerfile#L83)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

in other images you also have  such steps:
```
COPY install-pmdk.sh /opt/install-pmdk.sh
COPY install-libpmemobj-cpp.sh /opt/install-libpmemobj-cpp.sh
```

</blockquote></details>

great catch. done

**Review by karczex — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/dev-utils-kit/7#-:-Muk8LJODVcGmVhjRTzF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
